### ISSUE TITLE
`DiscoveryResults` aren't unique by multiple services on a single host

### ISSUE THREAD

**Issue by DazWilkin** [DazWilkin/akri#1]
**Describe the bug**

Creating multiple services on the same host using `avahi-publish` only discovers one service and creates one Akri Instance.

This is because the `DiscoveryResult` id (hash) is computed only from the host name but should be computed from service*host.

`protocols/zeroconf/map.rs` currently names `DiscoveryResult` using:

```rust
DiscoveryResult::new(service.host_name(), props, true)
```

But `service.host_name()` is the host name i.e. `workstation.local` and could run multiple services e.g. `freddie`, `louie`

**To Reproduce**

Multiple services deployed with `avahi-publish` aren't detected as multiple services because the `DiscoveryResult` (id|digest) value is computed from `service.host_name()` and this does not change for different services on the same host.

See:

```YAML
[{
  digest: "074bbf",
  properties: {
    "AKRI_ZEROCONF_DEVICE_NAME": "louie",
    "AKRI_ZEROCONF_DEVICE_HOST": "akri.local",
  }
}, DiscoveryResult {
  digest: "074bbf",
  properties: {
     "AKRI_ZEROCONF_DEVICE_NAME": "noisette",
     "AKRI_ZEROCONF_DEVICE_HOST": "akri.local"
  }
}, DiscoveryResult {
  digest: "074bbf",
  properties: {
    "AKRI_ZEROCONF_DEVICE_NAME": "artie",
    "AKRI_ZEROCONF_DEVICE_HOST": "akri.local",
  }
}, DiscoveryResult {
  digest: "074bbf",
  properties: {
    "AKRI_ZEROCONF_DEVICE_NAME": "freddie",
    "AKRI_ZEROCONF_DEVICE_HOST": "akri.local"
  }
}]
```

> **NOTE** The `digest` are the same (computed from `akri.local`) even though the services are distinct

**Expected behavior**

Expected each service to be uniquely identified and for Akri Instances to be created for each.
